language: go
os: linux
sudo: required
services:
- docker
go:
- 1.12.x
go_import_path: github.com/cloud-native-taiwan/labels-syncker
env:
- GO111MODULE=on
script:
- go mod download
- make
after_success:
- |
  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    ./out/labels-syncker --token=$ACCESS_TOKEN --config=labels.yml -v=2 --logtostderr
  fi